// Generated by tools/fontgen.py - do not edit.
#pragma once
#include "font.h"

extern const Font FONT_B10;  // helvB10.bdf
extern const Font FONT_B12;  // helvB12.bdf
extern const Font FONT_B14;  // helvB14.bdf
extern const Font FONT_B18;  // helvB18.bdf
extern const Font FONT_B24;  // helvB24.bdf
extern const Font FONT_R12;  // helvR12.bdf
extern const Font FONT_DIGITS;  // liberation-sans-bold-80-digits.bdf
