#!/usr/bin/env python3
"""Generate main/fonts.h and main/fonts_data.cpp from the BDF fonts in fonts/.

Usage: python3 tools/fontgen.py   (from anywhere; paths are repo-relative)

Only the characters listed per font are taken over, so the firmware does
not carry hundreds of unused glyphs. Re-run after changing FONTS below and
commit the regenerated files.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Printable ASCII, Latin-1 (German umlauts, ß, °, ...) and the typographic
# characters that commonly show up in notification titles.
TEXT = (
    list(range(0x20, 0x7F))
    + list(range(0xA0, 0x100))
    + [0x2013, 0x2014, 0x2018, 0x2019, 0x201A, 0x201C, 0x201D, 0x201E,
       0x2022, 0x2026, 0x20AC]
)
DIGITS = [ord(c) for c in "0123456789+"]

# (C name, BDF file, characters)
FONTS = [
    ("FONT_B10", "helvB10.bdf", TEXT),
    ("FONT_B12", "helvB12.bdf", TEXT),
    ("FONT_B14", "helvB14.bdf", TEXT),
    ("FONT_B18", "helvB18.bdf", TEXT),
    ("FONT_B24", "helvB24.bdf", TEXT),
    ("FONT_R12", "helvR12.bdf", TEXT),
    ("FONT_DIGITS", "liberation-sans-bold-80-digits.bdf", DIGITS),
]


def parse_bdf(path):
    """Return (ascent, descent, {codepoint: glyph dict})."""
    ascent = descent = None
    glyphs = {}
    lines = iter(path.read_text(encoding="latin-1").splitlines())
    for line in lines:
        key, _, rest = line.partition(" ")
        if key == "FONT_ASCENT":
            ascent = int(rest)
        elif key == "FONT_DESCENT":
            descent = int(rest)
        elif key == "STARTCHAR":
            g = {}
            for line in lines:
                key, _, rest = line.partition(" ")
                if key == "ENCODING":
                    g["cp"] = int(rest.split()[0])
                elif key == "DWIDTH":
                    g["adv"] = int(rest.split()[0])
                elif key == "BBX":
                    g["w"], g["h"], g["x"], g["y"] = map(int, rest.split())
                elif key == "BITMAP":
                    g["rows"] = [bytes.fromhex(next(lines).strip()) for _ in range(g["h"])]
                elif key == "ENDCHAR":
                    break
            if g.get("cp", -1) >= 0:
                glyphs[g["cp"]] = g
    return ascent, descent, glyphs


def main():
    header = [
        "// Generated by tools/fontgen.py - do not edit.",
        "#pragma once",
        '#include "font.h"',
        "",
    ]
    data = [
        "// Generated by tools/fontgen.py from the BDF files in fonts/ - do not edit.",
        "// Font licenses: see fonts/README.md.",
        '#include "fonts.h"',
        "",
    ]
    for name, file, chars in FONTS:
        ascent, descent, glyphs = parse_bdf(ROOT / "fonts" / file)
        missing = [hex(c) for c in chars if c not in glyphs]
        if missing:
            print(f"{file}: no glyph for {', '.join(missing)}")
        bitmap = bytearray()
        entries = []
        for cp in sorted(c for c in chars if c in glyphs):
            g = glyphs[cp]
            stride = (g["w"] + 7) // 8
            entries.append(
                f"    {{0x{cp:04X}, {len(bitmap)}, {g['w']}, {g['h']}, {g['x']}, "
                f"{g['y'] + g['h']}, {g['adv']}}},"
            )
            for row in g["rows"]:
                bitmap += row[:stride].ljust(stride, b"\0")
        low = name.lower()
        data.append(f"static const uint8_t {low}_bitmap[] = {{")
        for i in range(0, len(bitmap), 16):
            data.append("    " + " ".join(f"0x{b:02X}," for b in bitmap[i:i + 16]))
        data.append("};")
        data.append(f"static const FontGlyph {low}_glyphs[] = {{")
        data += entries
        data.append("};")
        data.append(
            f"const Font {name} = {{{low}_glyphs, {len(entries)}, {low}_bitmap, "
            f"{ascent}, {descent}}};"
        )
        data.append("")
        header.append(f"extern const Font {name};  // {file}")
    (ROOT / "main" / "fonts.h").write_text("\n".join(header) + "\n")
    (ROOT / "main" / "fonts_data.cpp").write_text("\n".join(data))
    print("wrote main/fonts.h, main/fonts_data.cpp")


if __name__ == "__main__":
    main()
